---
title: "Summary of results"
output: html_document
---

This document illustrates the querying and application of results derived and stored following the analysis results data model (ARDM). The tabs contain examples rendering the results from a descriptive, safety, and survival analysis standard into plots and tables.

```{r load, results='hide', message=FALSE, include=T, warning=FALSE}

# Load libraries
library(tidyverse)
library(DBI)
library(RSQLite)
library(here)
library(scales)
library(reactable)
library(gridExtra)
library(cowplot)

# Make sure path is relative
here::i_am("ARDM/applications/summary.Rmd")

# Load files necessary to create the tables and plots
source(here::here("ARDM", "applications", "plots.R"))
source(here::here("ARDM", "applications", "tables.R"))

# Open connection to the database
connection <- dbConnect(RSQLite::SQLite(), dbname = here::here("ARDM", "database", "ardm.sqlite"))

```

## {.tabset}

### Descriptive Statistics

#### Demographics

```{r demographics_continuous, fig.align='center'}
# Search for the data and include the treatment names
data <- dbGetQuery(connection, "SELECT * FROM descriptive_demographics_continuous
                                LEFT JOIN 
                                  (SELECT DISTINCT parameter_id, name FROM demographics_per_subject) 
                                  AS newtable1
                                USING 
                                (parameter_id)
                                LEFT JOIN 
                                  (SELECT treatment_id, treatment FROM treatments) AS newtable2 
                                USING 
                                (treatment_id)")

# Update margins
par(mar = c(4, 4, .1, .2))

# Plot the results
plot_boxplot(data)
```

```{r demographics_categorical, fig.align='center'}
# Search for the data and include the treatment names
data <- dbGetQuery(connection, "SELECT * FROM descriptive_demographics_categorical
                                LEFT JOIN 
                                  (SELECT DISTINCT parameter_id, name FROM demographics_per_subject) 
                                  AS newtable1
                                USING 
                                (parameter_id)
                                LEFT JOIN 
                                  (SELECT treatment_id, treatment FROM treatments) AS newtable2 
                                USING 
                                (treatment_id)")

# Update margins
par(mar = c(4, 4, .1, .2))

# Plot the results
plot_dotplot(data)
```

#### Baselines

```{r baselines_continuous, fig.align='center'}
# Search for the data and include the treatment names
data <- dbGetQuery(connection, "SELECT * FROM descriptive_baselines_continuous
                                LEFT JOIN 
                                  (SELECT DISTINCT parameter_id, name FROM baselines_per_subject) 
                                  AS newtable1
                                USING 
                                (parameter_id)
                                LEFT JOIN 
                                  (SELECT treatment_id, treatment FROM treatments) AS newtable2 
                                USING 
                                (treatment_id)")

# Update margins 
par(mar = c(4, 4, .1, .2))

plots <- purrr::map(unique(data$name), # Get the parameters
                function(x) {filtered_data <- data %>% dplyr::filter(name == x) # Filter by parameter
                            plot_boxplot(filtered_data) # Plot the results
                            }
                )
```

### Safety Analysis

```{r safety, fig.align='center'}
# Search for the data and include the treatment names
data <- dbGetQuery(connection, "SELECT * FROM crude_incidence
                                LEFT JOIN 
                                  (SELECT treatment_id, treatment FROM treatments) AS newtable 
                                USING (treatment_id)")
# Select the data to show                           
selected_data <- data %>%
  dplyr::select(study_id, treatment, SOC, PT, N_PT, P_PT) %>% 
  dplyr::distinct()

# Show the results table
create_AE_table(selected_data)
```

### Survival Analysis

```{r survival, fig.align='center'}
# Search for the data 
data <- dbGetQuery(connection, "SELECT * FROM survival_analysis")

# Update margins 
par(mar = c(4, 4, .1, .2))

# Plot the results
plot_km(data, add_median = FALSE)
```

```{r survival_filtered, fig.align='center'}
# Optional: filter the data  
filtered_data <- data %>% 
  dplyr::filter(!strata  %in% "treatment=Xanomeline low dose")

# Plot the filtered results
plot_km(filtered_data, add_median = FALSE, add_median_treatment)
```

```{r survival_risk_table, fig.align='center'}
# Update margins 
par(mar = c(4, 4, .1, .2))

# Plot for the filtered results
plot <- plot_km(filtered_data, 
                add_median = TRUE, 
                add_median_treatment = "Xanomeline high dose")

# Plot for the risk table
time_index <- c(0,50,100,150,200)
table <- at_risk_table(time_index,filtered_data)

plot_grid(plot, table, align = "h", axis = "l", nrow = 2)
```

```{r, echo=FALSE}
dbDisconnect(connection)
```

